/// Flutter icons CityScapes
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CityScapes
///      fonts:
///       - asset: fonts/CityScapes.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CityScapes {
  CityScapes._();

  static const _kFontFam = 'CityScapes';
  static const String? _kFontPkg = null;

  static const IconData bat3 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bat_many = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bat1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bat2 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
